environment = "prd"
aws_s3_bucket_prefix="<AMAZON_S3_BUCKET_PREFIX>"
aws_ec2_ami_id="<AMAZON_EC2_AMI_ID>"
azure_subscription_id="<AZURE_SUBSCRIPTION_ID>"
azure_storage_account_prefix="<AZURE_STORAGE_PREFIX>"
azure_vm_image_id="<AZURE_VM_IMAGE_ID>"
my_ip="<Your_Public_IP>"